apiVersion: v1
kind: Service
metadata:
  name: cloud-native-data-pipeline-service
  labels:
    app: cloud-native-data-pipeline
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: cloud-native-data-pipeline